services:
  postgres:
    image: postgres:17
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d nestdb"]
      interval: 10s
      retries: 5
      start_period: 5s
volumes:
  postgres_data: